#!/bin/bash --login
#PBS -l walltime=02:00:00
#PBS -l select=1:ncpus=4
#PBS -N split_read1
#PBS -A d411-training
#PBS -j oe

### script start

echo "setting temporary directory"
mkdir -p ~/qiime_tmp
export TMPDIR=~/qiime_tmp

echo "loading virtual environment"
source deactivate
source activate qiime1

echo "creating and cd to output directory"
mkdir -p ~/output/test/
cd ~/output/test/

# QIIME Code

echo "Demultiplexing with QIIME defaults"
echo "Full data set"
# note: the command below is broken across several lines using backslashes (\)
# you could also have the code on a single line with spaces instead
 split_libraries_fastq.py \
-i ~mbaron/2019/read1.fastq.gz \
-b ~mbaron/2019/index.fastq.gz \
-m ~/project/map.tsv \
-o ~.slout \
--rev_comp_barcode --rev_comp_mapping_barcodes

echo "closing environment"
source deactivate

### script end
